### ISSUE TITLE
Installed on Picroft but no entries in home.mycroft.ai skills

### ISSUE THREAD

**Issue by bgarr33434** [ejstacey/skill-subsonic-media#6] opened 2018-06-26 23:32 UTC
don't know where to put credentials and IP address?  Perhaps in mycroft.conf?  WHat should the entries be?

**Comment by ejstacey** [comment] 2018-06-26 23:47
If your picroft is up to date, then this module won't work, due to a python 3 upgrade being needed (#5 covers this).  The entries should be on home.mycroft.ai, but if they're not, I am guessing the module isn't actually loading properly (possibly due to python 3 as above, or something else isn't properly installing as a dependency).

All that said, the settings look like this:

{"username": "<username>", "server": "<IP address>", "path": "<subdir if there's one, otherwise just blank>", "password": "<password>", "port": "<port number>"}

That can go in settings.json in your /opt/mycroft/skills/skill-subsonic-media directory which I believe exists on picroft.  Create the file if necessary.

As I said though, if it's not showing up on the home.mycroft.ai skills page after loading the module (and reloading the page), I'm guessing it's not loading.  You can check that out by grepping for subsonic in the mycroft-skills.log file.

Here is info for finding log files on the picroft: https://mycroft.ai/documentation/troubleshooting/#picroft

Can you have a look at the logs and tell me what it says or paste what it shows for subsonic?  Thanks!

**Comment by bgarr33434** [comment] 2018-06-27 01:07
Yeah, that is the issue.  I saw some python2.7 remarks in the error log.  I'll look for a different skill for playing music for my demo tape.  Thanks.

Regards,

Brian Garr
561.271.4750
@garrbrian

**Comment by ejstacey** [comment] 2018-06-27 14:53
Dupe of #5.

**Closed by ejstacey** 2018-06-27 14:53 UTC
